variables:
    IMAGE_NAME: admin-panel-client
    IMAGE_TAG: 1.0.1
    SMS_Message: "admin-panel-client-->Build-OK"
    REGISTRY_HOST: $DOCKER_PRIVATE_REGISTRY_IP:$DOCKER_PRIVATE_REGISTRY_PORT

stages:
  - Code Quality
  - Build
  - Deploy
  - Notifications

sonarqube-analysis:
  stage: Code Quality
  image: $REGISTRY_HOST/repository/tech1a-docker-registry/mcr.microsoft.com/dotnet/sdk:6.0
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
    GIT_DEPTH: "0"  
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
      - "apt-get update"
      - "apt-get install --yes openjdk-11-jre nuget gss-ntlmssp"
      - "dotnet tool install --global dotnet-sonarscanner"
      - "export PATH=\"$PATH:$HOME/.dotnet/tools\""
      - "dotnet sonarscanner begin /k:\"$IMAGE_NAME\" /d:sonar.login=\"$SONAR_User\" /d:sonar.password=\"$SONAR_PASSWORD\"  /d:\"sonar.host.url=$SONAR_HOST_URL\" "
      - "dotnet restore "
      - "dotnet build "
      - "dotnet sonarscanner end /d:sonar.login=\"$SONAR_User\" /d:sonar.password=\"$SONAR_PASSWORD\""
  allow_failure: true
  #only:
    #- main

build:
    stage: Build
    image: $REGISTRY_HOST/repository/tech1a-docker-registry/docker:20.10.17
    services:
    - name: $REGISTRY_HOST/repository/tech1a-docker-registry/docker:20.10.17-dind
      alias: docker
      entrypoint: [ "sh", "-c", "dockerd-entrypoint.sh $DOCKER_DAEMON_OPTIONS" ]
    variables:
      DOCKER_DAEMON_OPTIONS: "--insecure-registry=$REGISTRY_HOST"
    needs:
      - job: sonarqube-analysis
    script:
        - docker login -u "$DOCKER_PRIVATE_REGISTRY_USER" -p "$DOCKER_PRIVATE_REGISTRY_PASSWORD" "http://$REGISTRY_HOST"
        - docker build -t $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:$IMAGE_TAG .
        - docker push $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:$IMAGE_TAG
        - docker tag $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:$IMAGE_TAG $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:latest
        - docker push $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:latest
    # only:
    # - main 
    after_script:
        -  echo "Build succeeded"

deploy:
  stage: Deploy
  variables: 
    DOCKER_HOST: "ssh://$DOCKER_SWARM_IP"
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - echo "$DOCKER_SWARM_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DOCKER_SWARM_IP >> ~/.ssh/known_hosts
  script:
    - docker stack rm $IMAGE_NAME 
    - docker stack deploy -c docker-compose.yml $IMAGE_NAME
  needs:
    - job: build
  retry: 2

SMS:
  stage: Notifications
  image: $DOCKER_PRIVATE_REGISTRY_IP:$DOCKER_PRIVATE_REGISTRY_PORT/repository/tech1a-docker-registry/curlimages/curl
  script:
    - curl -X POST "https://my.candoosms.com/services/URLService/URN/?username=$SMS_PROVIDER_USER&password=$SMS_PROVIDER_PASSWORD&command=send&src=$SMS_SEND_SRC&destinations=$SMSGroup&body=$SMS_Message&flash=0"
  needs:
    - job: deploy
  #only:
    #- main


