import { ColDef } from "ag-grid-community";
import columnModel from "./columns-model";
import { ModuleIdentifier } from "./Module-Identifier";
import ToggleButton from "components/marketer-app/marketer-contract/toggle-button";
import RoleToggleButton from "components/users-management/roles/role-toggle-button";
import ToggleButtonUsers from "components/users-management/users/toggle-button";
import ToogleCustomerPAM from "components/customer-management/customer/edit-customer-PAM";

const Modules = Object.values(ModuleIdentifier);
export type ModulesType = (typeof Modules)[number];

interface ColDefType extends ColDef {
  colId: (typeof columnModel)[number]["colId"];
  children?: ColDefType[];
}
export type ModularColsDefType = {
  [key in ModulesType]?: ColDefType[];
};

export const modularColsDef: ModularColsDefType = {
  "book-building": [
    { colId: "checkbox" },
    { colId: "instrumentId" },
    { colId: "faInsCode" },
    { colId: "faInsName" },
    { colId: "maxQuantity" },
    { colId: "minPrice" },
    { colId: "maxPrice" },
    { colId: "fromActiveDateTime" },
    { colId: "toActiveDateTime" },
    { colId: "createdBy" },
    { colId: "createDateTime" },
    { colId: "updatedBy" },
    { colId: "updatedDateTime" },
  ],
  "customer-management_customer": [
    { colId: "checkbox" },
    { colId: "detail-opener" },
    { colId: "uniqueId" },
    { colId: "title" },
    { colId: "personTypeTitle" },
    { colId: "personOriginTitle" },
    { colId: "countryName" },
    { colId: "foreignCSDCode" },
    { colId: "branchTitle" },
    { colId: "regentTitle" },
    { colId: "marketerTitle" },
    { colId: "isActive" },
    { colId: "isDeleted" },
    { colId: "createDateTime" },
    { colId: "customer-detail" },
  ],
  "customer-management_customer_detail": [
    { colId: "genderTitle" },
    { colId: "isProfessional" },
    {
      colId: "isPAM",
      cellRendererSelector: () => {
        return {
          component: (rowData: any) => (
            <ToogleCustomerPAM
              data={{
                isActive: rowData?.data?.isPAMTrader,
                id: rowData?.data?.id,
              }}
            />
          ),
        };
      },
    },
    { colId: "sejamStatusTitle" },
    { colId: "isDeceased" },
    { colId: "isDissolved" },
    { colId: "adminNote" },
    { colId: "updateDateTime" },
  ],
  "customer-management_private_person": [
    { colId: "checkbox" },
    { colId: "uniqueId" },
    { colId: "firstName" },
    { colId: "lastName" },
    { colId: "fatherName" },
    { colId: "genderTitle" },
    { colId: "seriShChar" },
    { colId: "seriSh" },
    { colId: "shSerial" },
    { colId: "shNumber" },
    { colId: "birthDate" },
    { colId: "birthPlace" },
    { colId: "issuePlace" },
    { colId: "isDeceased" },
    { colId: "deceasedDate" },
    { colId: "createDateTime" },
    { colId: "updateDateTime" },
  ],
  "customer-management_legal_person": [
    { colId: "checkbox" },
    { colId: "uniqueId", headerName: "شناسه ملی" },
    { colId: "companyName" },
    { colId: "registerNumber" },
    { colId: "registerPlace" },
    { colId: "registerDate" },
    { colId: "evidenceReleaseCompany" },
    { colId: "evidenceReleaseDate" },
    { colId: "economicCode" },
    { colId: "evidenceExpirationDate" },
    { colId: "legalPersonTypeCategoryTitle" },
    { colId: "legalPersonTypeSubCategoryTitle" },
    { colId: "isDissolved" },
    { colId: "createDateTime" },
    { colId: "updateDateTime" },
  ],
  "customer-management_private_portfolio": [
    { colId: "checkbox" },
    { colId: "privatePortfolioTitle" },
    { colId: "bourseCode" },
    { colId: "relatedCustomerTitle" },
    { colId: "relatedCustomerUniqueId" },
    { colId: "assetManagerTitle" },
    { colId: "assetManagerUniqueId" },
    { colId: "managementTypeTitle" },
    { colId: "managementStartDate" },
    { colId: "managementEndDate" },
    { colId: "isExpired" },
    { colId: "createDateTime" },
    { colId: "updateDateTime" },
  ],
  "customer-management_bank_account": [
    { colId: "checkbox" },
    { colId: "customerTitle" },
    { colId: "customerUniqueId" },
    { colId: "customerPhoneNumber" },
    { colId: "sheba" },
    { colId: "accountNumber" },
    { colId: "typeTitle" },
    { colId: "bankTitle" },
    { colId: "branchCode" },
    { colId: "branchTitle" },
    { colId: "cityTitle" },
    { colId: "isDefault" },
    { colId: "isFromSejam" },
    { colId: "isConfirmed" },
    { colId: "description" },
    { colId: "createDateTime" },
    { colId: "updateDateTime" },
  ],
  "customer-management_agent": [
    { colId: "checkbox" },
    { colId: "uniqueId" },
    { colId: "firstName" },
    { colId: "lastName" },
    { colId: "description" },
    { colId: "createDateTime" },
    { colId: "updateDateTime" },
  ],
  "customer-management_agent_relation": [
    { colId: "checkbox" },
    { colId: "customerUniqueId" },
    { colId: "customerTitle" },
    { colId: "agentUniqueId" },
    { colId: "agentTitle" },
    { colId: "agentTypeTitle" },
    { colId: "isConfirmed" },
    { colId: "startDate" },
    { colId: "expirationDate" },
    { colId: "description" },
    { colId: "createDateTime" },
  ],
  "customer-management_branch_history": [
    { colId: "customerTitle" },
    { colId: "customerUniqueId" },
    { colId: "branchTitle" },
    { colId: "branchTypeTitle" },
    { colId: "tbsBranchId" },
    { colId: "tbsBranchTitle" },
    { colId: "subsidiaryTitle" },
    { colId: "changeDateTime" },
  ],
  "customer-management_marketer_history": [
    { colId: "customerTitle" },
    { colId: "customerUniqueId" },
    { colId: "marketerTypeTitle" },
    { colId: "marketerTitle" },
    { colId: "tbsMarketerId" },
    { colId: "tbsMarketerTitle" },
    { colId: "changeDateTime" },
  ],
  "commission-management_category": [
    { colId: "id" },
    { colId: "marketCode" },
    { colId: "marketTitle" },
    { colId: "offerTypeTitle" },
    { colId: "sideCode" },
    { colId: "sideTitle" },
    { colId: "settlementDelayCode" },
    { colId: "settlementDelayTitle" },
    { colId: "customerTypeCode" },
    { colId: "customerTypeTitle" },
    { colId: "customerCounterSideCode" },
    { colId: "customerCounterSideTitle" },
  ],
  "commission-management_detail": [
    { colId: "checkbox" },
    {
      colId: "brokerCommission",
      children: [
        { colId: "brokerCommissionCoeff" },
        { colId: "minBrokerCommissionValue" },
        { colId: "maxBrokerCommissionValue" },
      ],
    },
    {
      colId: "brokerCmdCommission",
      children: [
        { colId: "brokerCmdFundCoeff" },
        { colId: "maxBrokerCmdFundValue" },
      ],
    },
    {
      colId: "seoControlCommission",
      children: [
        { colId: "seoControlCommissionCoeff" },
        { colId: "maxSeoControlCommissionValue" },
      ],
    },
    {
      colId: "csdCommission",
      children: [
        { colId: "csdCommissionCoeff" },
        { colId: "maxCsdCommissionValue" },
      ],
    },
    {
      colId: "tmcCommission",
      children: [
        { colId: "tmcCommissionCoeff" },
        { colId: "maxTmcCommissionValue" },
      ],
    },
    {
      colId: "bourseCommission",
      children: [
        { colId: "bourseCommissionCoeff" },
        { colId: "maxBourseCommissionValue" },
      ],
    },
    {
      colId: "rayanCommission",
      children: [
        { colId: "rayanCommissionCoeff" },
        { colId: "maxRayanCommissionValue" },
      ],
    },
    {
      colId: "accessCommission",
      children: [
        { colId: "accessCommissionCoeff" },
        { colId: "totalCommissionCoeff" },
        { colId: "maxAccessCommissionValue" },
      ],
    },
    {
      colId: "taxCommission",
      children: [{ colId: "addedValueTax" }, { colId: "maxTaxValue" }],
    },
    { colId: "taxCoeff" },
    { colId: "charge" },
    { colId: "netTradeValueCoeff" },
    { colId: "beginningEffectingDate" },
    { colId: "endEffectingDate" },
    { colId: "deleted" },
    { colId: "lastUpdaterUserId" },
    { colId: "lastUpdateDateTime" },
  ],
  "commission-management_instrument_result": [
    { colId: "id" },
    { colId: "bourseCode", sort: "desc" },
    { colId: "bourseTitle" },
    { colId: "instrumentTypeCode" },
    { colId: "instrumentTypeTitle" },
    { colId: "sectorCode" },
    { colId: "sectorTitle" },
    { colId: "subSectorCode" },
    { colId: "subSectorTitle" },
    { colId: "inventoryStatus" },
    { colId: "instrumentTypeDescription" },
  ],
  "commission-management_instrument": [
    { colId: "checkbox" },
    { colId: "id" },
    { colId: "bourseTitle" },
    { colId: "instrumentTypeCode" },
    { colId: "instrumentTypeTitle" },
    { colId: "sectorCode" },
    { colId: "sectorTitle" },
    { colId: "subSectorCode" },
    { colId: "subSectorTitle" },
    { colId: "deleted" },
    { colId: "instrumentTypeDescription" },
  ],
  "commission-management_abstract_symbols": [
    { colId: "instrumentId" },
    { colId: "faInsCode" },
    { colId: "offerTypeCode" },
    { colId: "sideCode" },
    { colId: "customerTypeCode" },
    { colId: "customerCounterSideCode" },
    { colId: "totalCommissionCoeff" },
    { colId: "netTradeCoeff" },
    { colId: "breakEvenPriceCoeff" },
    { colId: "beginningEffectingDate" },
    { colId: "endEffectingDate" },
    { colId: "valid" },
    { colId: "deleted" },
  ],
  "commission-management_full_symbols": [
    { colId: "instrumentId", cellRenderer: "agGroupCellRenderer" },
    { colId: "faInsCode" },
    { colId: "offerTypeCode" },
    { colId: "sideCode" },
    { colId: "settlementDelayCode" },
    { colId: "customerTypeCode" },
    { colId: "customerCounterSideCode" },
    { colId: "netBrokerCommissionCoeff" },
    { colId: "totalCommissionCoeff" },
    { colId: "netTradeCoeff" },
    { colId: "breakEvenPriceCoeff" },
    { colId: "beginningEffectingDate" },
    { colId: "endEffectingDate" },
    { colId: "valid" },
    { colId: "deleted" },
  ],
  "commission-management_full_symbols_detail": [
    { colId: "category" },
    { colId: "broker" },
    { colId: "access" },
    { colId: "brokerCmdFund" },
    { colId: "bourse" },
    { colId: "seoControl" },
    { colId: "csd" },
    { colId: "tmc" },
    { colId: "rayan" },
    { colId: "tax", cellStyle: { direction: "ltr" } },
    { colId: "addedValue" },
    { colId: "charge" },
    { colId: "inventory" },
    { colId: "inventoryAddedValueTax" },
  ],
  "csdi-portfo_asset_switch_report": [
    { colId: "tradingCode" },
    { colId: "nationalId" },
    { colId: "customerTitle" },
    { colId: "bourseCode" },
    { colId: "instrumentId" },
    { colId: "faInsCode" },
    { colId: "faInsName" },
    { colId: "customerType" },
    { colId: "shareChange" },
    { colId: "shareCount" },
    { colId: "changeType" },
    { colId: "effectiveDate" },
  ],
  "csdi-portfo_freezed_asset": [
    { colId: "tradingCode" },
    { colId: "nationalId" },
    { colId: "customerTitle" },
    { colId: "bourseCode" },
    { colId: "personType" },
    { colId: "instrumentId" },
    { colId: "faInsCode" },
    { colId: "faInsName" },
    { colId: "isFreezed" },
    { colId: "effectiveDate" },
  ],
  "csdi-portfo": [
    { colId: "tradingCode" },
    { colId: "nationalId" },
    { colId: "customerTitle" },
    { colId: "bourseCode" },
    { colId: "instrumentId" },
    { colId: "faInsCode" },
    { colId: "faInsName" },
    { colId: "customerType" },
    { colId: "shareCount" },
    { colId: "lastPrice", hide: true },
    { colId: "closingPrice" },
    { colId: "netValueByClosingPrice" },
    { colId: "netValueByLastPrice", hide: true },
    { colId: "shareChange" },
    { colId: "changeType" },
    { colId: "isFreezed" },
    { colId: "effectiveDate" },
  ],
  "csdi-portfo_comparison": [
    { colId: "faInsCode" },
    {
      colId: "first-date",
      children: [
        { colId: "firstshareCount" },
        { colId: "firstlastPrice" },
        { colId: "firstclosingPrice", hide: true },
        { colId: "firstnetValuebyClosingPrice", hide: true, aggFunc: "sum" },
        { colId: "firstnetValuebyLastPrice", aggFunc: "sum" },
        { colId: "firstClosingPricePercentage", hide: true },
        { colId: "firstLastPricePercentage" },
        { colId: "firstClosingPricePercentage" },
      ],
    },
    {
      colId: "second-date",
      children: [
        { colId: "secondshareCount" },
        { colId: "secondlastPrice" },
        { colId: "secondclosingPrice", hide: true },
        { colId: "secondnetValuebyClosingPrice", hide: true, aggFunc: "sum" },
        { colId: "secondnetValuebyLastPrice", aggFunc: "sum" },
        { colId: "secondClosingPricePercentage", hide: true },
        { colId: "secondLastPricePercentage" },
        { colId: "secondClosingPricePercentage" },
      ],
    },
  ],
  "csdi-portfo_switch_report": [
    { colId: "tradingCode" },
    { colId: "nationalId" },
    { colId: "customerTitle" },
    { colId: "bourseCode" },
    { colId: "instrumentId" },
    { colId: "faInsCode" },
    { colId: "faInsName" },
    { colId: "customerType" },
    { colId: "shareChange" },
    { colId: "shareCount" },
    { colId: "changeType" },
    { colId: "effectiveDate" },
  ],
  "market-rules-management": [
    { colId: "checkbox" },
    { colId: "id", cellRenderer: "agGroupCellRenderer" },
    { colId: "name", headerName: "نام قانون" },
    { colId: "errorMessage" },
    { colId: "sequenceNumber" },
    { colId: "createDateTime" },
    { colId: "createBy" },
    { colId: "updatedDateTime" },
    { colId: "updatedBy" },
    { colId: "userIP" },
  ],
  "marketer-app_marketers": [
    { colId: "checkbox" },
    { colId: "UniqueId", headerName: "کد ملی بازاریاب" },
    { colId: "Title", headerName: "عنوان بازاریاب" },
    { colId: "TypeTitle" },
    { colId: "Mobile" },
    { colId: "SubsidiaryTitle" },
    { colId: "BranchTitle" },
    { colId: "ReagentRefLink" },
    { colId: "MarketerRefLink" },
    {
      colId: "IsActive",
      cellRendererSelector: () => {
        return {
          component: (rowData: any) => (
            <ToggleButton
              data={{
                isActive: rowData?.data?.IsActive,
                id: rowData?.data?.id,
              }}
            />
          ),
        };
      },
    },
  ],
  "marketer-app_reconcilation": [
    { colId: "MarketerFirstName", cellRenderer: "agGroupCellRenderer" },
    { colId: "MarketerLastNAme" },
    { colId: "TradeSide" },
    { colId: "TradeCount" },
    { colId: "TradeDate" },
  ],
  "marketer-app_reconcilation_detail": [
    { colId: "FollowerMarketerID" },
    { colId: "CommissionCoefficient" },
    { colId: "StartDate" },
    { colId: "EndDate" },
    { colId: "GCreateDate" },
    { colId: "GUpdateDate" },
  ],
  "marketer-app_relations": [
    { colId: "checkbox" },
    { colId: "LeaderMarketerID", cellRenderer: "agGroupCellRenderer" },
    { colId: "FollowerMarketerName" },
    { colId: "LeaderMarketerName" },
  ],
  "marketer-app_relations_detail": [
    { colId: "FollowerMarketerID" },
    { colId: "CommissionCoefficient" },
    { colId: "StartDate" },
    { colId: "EndDate" },
    { colId: "CreateDate" },
    { colId: "UpdateDate" },
  ],
  "marketer-app_subusers": [
    { colId: "FirstName" },
    { colId: "LastName" },
    { colId: "FirmTitle" },
    { colId: "TotalPureVolume" },
    { colId: "TotalFee" },
    { colId: "Mobile" },
    { colId: "BankAccountNumber" },
    { colId: "Email" },
    { colId: "RegisterDate" },
  ],
  "marketer-app_marketerContract": [
    { colId: "checkbox" },
    { colId: "ContractID" },
    { colId: "MarketerID" },
    { colId: "Title", headerName: "عنوان بازاریاب" },
    { colId: "CalculationBaseType" },
    { colId: "CoefficientBaseType" },
    { colId: "ContractType" },
    { colId: "Description" },
    { colId: "StartDate" },
    { colId: "EndDate" },
    { colId: "marketerContract-detail" },
  ],
  "marketer-app_recite": [
    { colId: "checkbox" },
    { colId: "MarketerID" },
    { colId: "Period" },
    { colId: "Plan" },
    { colId: "Status" },
    { colId: "marketer-recite-detail" },
  ],
  "marketer-app_marketerContract_detail_deduction": [
    { colId: "ContractID" },
    { colId: "MarketerID" },
    { colId: "Title", headerName: "عنوان بازاریاب" },
    { colId: "CollateralCoefficient" },
    { colId: "TaxCoefficient" },
    { colId: "InsuranceCoefficient" },
    { colId: "ReturnDuration" },
  ],
  "marketer-app_marketerContract_detail_coefficient": [
    { colId: "ContractID" },
    { colId: "MarketerID" },
    { colId: "Title", headerName: "عنوان بازاریاب" },
    { colId: "CoefficientPercentage" },
    { colId: "HighThreshold" },
    { colId: "LowThreshold" },
    { colId: "StepNumber" },
    { colId: "IsCmdConcluded" },
  ],
  netflow_cleared_trade: [
    { colId: "ticket", cellRenderer: "agGroupCellRenderer" },
    { colId: "date" },
    { colId: "symbol" },
    { colId: "instrumentId" },
    { colId: "price" },
    { colId: "shares" },
    { colId: "settlementValue" },
  ],
  netflow_cleared_trade_detail: [
    { colId: "brokerCommission" },
    { colId: "brfCommission" },
    { colId: "bourseCommission" },
    { colId: "seoCommission" },
    { colId: "tmcCommission" },
    { colId: "accessCommission" },
    { colId: "csdCommission" },
    { colId: "rayanBourseCommission" },
    { colId: "inventoryCommission" },
    { colId: "tax" },
    { colId: "vatCommission" },
    { colId: "vtsCommission" },
    { colId: "farCommission" },
  ],
  netflow_clearing_Range: [
    { colId: "georgianTradeDate" },
    { colId: "enTierName" },
    { colId: "brokerCode" },
    { colId: "brokerName", cellRenderer: "agGroupCellRenderer" },
    { colId: "settlementDelay" },
    { colId: "buy" },
    { colId: "sell" },
    { colId: "sellerInterest" },
    { colId: "buyerInterest" },
    { colId: "credit" },
    { colId: "debit" },
    { colId: "sellerBalance" },
    { colId: "buyerBalance" },
  ],
  netflow_clearing_Range_detail: [
    { colId: "type" },
    { colId: "brokerCommission" },
    { colId: "brfCommission" },
    { colId: "accessCommission" },
    { colId: "seoCommission" },
    { colId: "tmcCommission" },
    { colId: "csdCommission" },
    { colId: "rayanBourseCommission" },
    { colId: "bourseCommission" },
    { colId: "inventoryCommission" },
    { colId: "farCommission" },
    { colId: "tax" },
    { colId: "vatCommission" },
    { colId: "vtsCommission" },
  ],
  netflow_rules: [
    { colId: "name", cellRenderer: "agGroupCellRenderer" },
    { colId: "startDate" },
    { colId: "endDate" },
    { colId: "symbol" },
    { colId: "buyerCode" },
    { colId: "sellerCode" },
    { colId: "settlementDelay" },
  ],
  netflow_rules_detail: [
    { colId: "netflow-rules-detail-type" },
    { colId: "accountCommission" },
    { colId: "seoCommission" },
    { colId: "tmcCommission" },
    { colId: "csdCommission" },
    { colId: "rayanBourseCommission" },
    { colId: "bourseCommission" },
    { colId: "brokerCommission" },
    { colId: "tax" },
    { colId: "vatCommission" },
    { colId: "vtsCommission" },
    { colId: "side" },
  ],
  netflow_trades_report: [
    { colId: "fullName", cellRenderer: "agGroupCellRenderer" },
    { colId: "sideTitle" },
    { colId: "symbol" },
    { colId: "settlementValue" },
    { colId: "price" },
    { colId: "shares" },
    { colId: "bourseCode" },
    { colId: "tradeCode" },
    { colId: "settlementDelay" },
    { colId: "stationName" },
    { colId: "stationCode" },
    { colId: "tradeDate" },
    {
      colId: "bourseCommission",
      valueGetter: "data.feeDetail.bourseCommission",
      hide: true,
    },
    {
      colId: "seoCommission",
      valueGetter: "data.feeDetail.seoCommission",
      hide: true,
    },
    {
      colId: "tmcCommission",
      valueGetter: "data.feeDetail.tmcCommission",
      hide: true,
    },
    {
      colId: "accessCommission",
      valueGetter: "data.feeDetail.accessCommission",
      hide: true,
    },
    {
      colId: "csdCommission",
      valueGetter: "data.feeDetail.csdCommission",
      hide: true,
    },
    {
      colId: "vatCommission",
      valueGetter: "data.feeDetail.vatCommission",
      hide: true,
    },
    {
      colId: "brokerCommission",
      valueGetter: "data.feeDetail.brokerCommission",
      hide: true,
    },
    {
      colId: "rayanBourseCommission",
      valueGetter: "data.feeDetail.rayanBourseCommission",
      hide: true,
    },
    {
      colId: "brfCommission",
      valueGetter: "data.feeDetail.brfCommission",
      hide: true,
    },
    {
      colId: "inventoryCommission",
      valueGetter: "data.feeDetail.inventoryCommission",
      hide: true,
    },
    { colId: "tax", valueGetter: "data.feeDetail.tax", hide: true },
    {
      colId: "vtsCommission",
      valueGetter: "data.feeDetail.vtsCommission",
      hide: true,
    },
    {
      colId: "farCommission",
      valueGetter: "data.feeDetail.farCommission",
      hide: true,
    },
  ],
  netflow_trades_report_detail: [
    { colId: "bourseCommission" },
    { colId: "seoCommission" },
    { colId: "tmcCommission" },
    { colId: "csdCommission" },
    { colId: "vatCommission" },
    { colId: "brokerCommission" },
    { colId: "accessCommission" },
    { colId: "brfCommission" },
    { colId: "rayanBourseCommission" },
    { colId: "inventoryCommission" },
    { colId: "tax" },
    { colId: "vtsCommission" },
    { colId: "farCommission" },
  ],
  "oms-timetable": [
    { colId: "instrumentGroupId" },
    { colId: "tradingSessionDate" },
    { colId: "tradingDayInsGroupTitle" },
    { colId: "eventTriggerTime" },
    { colId: "afterOpeningInsGroupTitle" },
    { colId: "eventDate" },
    { colId: "dateReceived" },
  ],
  "oms-session": [
    { colId: "sessionStatusCode" },
    { colId: "sessionStatusTitle" },
    { colId: "startDate" },
    { colId: "endDate" },
  ],
  "online-registration": [
    { colId: "checkbox" },
    { colId: "uniqueId", cellRenderer: "agGroupCellRenderer" },
    { colId: "mobileNumber" },
    { colId: "personTypeTitle" },
    { colId: "marketerRefCode" },
    { colId: "marketerTitle" },
    { colId: "reagentTitle" },
    { colId: "agentUniqueId" },
    { colId: "isSejami" },
    { colId: "sejamStatusCodeTitle" },
    { colId: "registrationStateCodeTitle" },
    { colId: "isTbsInserted" },
    { colId: "isTBSDocsInserted" },
    { colId: "online-registration-detail" },
  ],
  "online-registration_detail": [
    { colId: "email" },
    { colId: "branchTitle" },
    { colId: "countryName" },
    { colId: "foreignCSDCode" },
    { colId: "personOriginTitle" },
    { colId: "riskLevelTitle" },
    { colId: "sejamToken" },
    { colId: "changeReasonDescription" },
    { colId: "createDateTime" },
    { colId: "updateDateTime" },
  ],
  "online-cancel": [
    { colId: "instrumentId", cellRenderer: "agGroupCellRenderer" },
    { colId: "instrumentGroupIdentification" },
    { colId: "faInsCode" },
    { colId: "orderSideTitle" },
    { colId: "idOfTheBrokersOrderEntryServer" },
    { colId: "orderOriginTitle" },
    { colId: "orderTechnicalOriginTitle" },
    { colId: "userRequestDateTime" },
    { colId: "errorText" },
  ],
  "online-cancel_detail": [
    { colId: "id" },
    { colId: "idOfBrokerIssuingTheOrder" },
    { colId: "userId" },
    { colId: "userIP" },
    { colId: "sourceOfRequestTitle" },
    { colId: "tradingDateTime" },
    { colId: "errorCode" },
  ],
  "online-orders": [
    { colId: "checkbox" },
    { colId: "customerTitle", cellRenderer: "agGroupCellRenderer" },
    { colId: "faInsCode" },
    { colId: "orderSideTitle" },
    { colId: "price" },
    { colId: "quantity" },
    { colId: "exequtedQuantity" },
    { colId: "remainingQuantity" },
    { colId: "orderStatusTitle" },
    { colId: "orderTypeTitle" },
    { colId: "validityTypeTitle" },
    { colId: "userRequestDateTime" },
    { colId: "receiveResponseFromCapServerDateTime" },
  ],
  "online-trades": [
    { colId: "customerTitle", cellRenderer: "agGroupCellRenderer" },
    { colId: "userTitle" },
    { colId: "traderId" },
    { colId: "faInsCode" },
    { colId: "isCanceled" },
    { colId: "orderSideTitle" },
    { colId: "tradePrice" },
    { colId: "tradeQuantity" },
    { colId: "tradeDate" },
    { colId: "tradeTime" },
    { colId: "applicationSourceName" },
  ],
  "online-trades_detail": [
    { colId: "userId" },
    { colId: "customerNationalId" },
    { colId: "customerId" },
    { colId: "tradeId" },
    { colId: "instrumentId" },
    { colId: "orderId" },
  ],
  portfo_detail: [
    { colId: "id" },
    { colId: "transactionId" },
    { colId: "transactionTitle" },
    { colId: "instrumentId" },
    { colId: "faInsCode" },
    { colId: "currentShareCount" },
    { colId: "sellableShareCount" },
    { colId: "changeQuantity" },
    { colId: "openBuyOrder" },
    { colId: "openSellOrder" },
    { colId: "intradayBuy" },
    { colId: "intradaySell" },
    { colId: "remainAssetCount" },
    { colId: "transactionDateTime" },
    { colId: "effectiveDate" },
  ],
  "portfo-asset_switch_request": [
    { colId: "checkbox" },
    { colId: "tradingCode" },
    { colId: "uniqueId", cellRenderer: "agGroupCellRenderer" },
    { colId: "title" },
    { colId: "bourseCode" },
    { colId: "instrumentId" },
    { colId: "faInsCode" },
    { colId: "faInsName" },
    { colId: "status" },
    { colId: "description" },
    { colId: "username" },
    { colId: "createDateTime" },
    { colId: "updateDateTime" },
  ],
  "portfo-asset_switch_request_detail": [
    { colId: "userFirstName" },
    { colId: "userLastName" },
    { colId: "userUniqueId" },
  ],
  "portfo-customer_to_broker": [
    { colId: "tradingCode" },
    { colId: "nationalId" },
    { colId: "bourseCode" },
    { colId: "customerTitle" },
    { colId: "portfolioValueByClosingPrice" },
    { colId: "portfolioValueByLastPrice", hide: true },
    { colId: "portfolioWeightByClosingPrice" },
    { colId: "portfolioWeightByLastPrice", hide: true },
  ],
  intraday: [
    { colId: "tradingCode" },
    { colId: "nationalId" },
    { colId: "bourseCode" },
    { colId: "customerTitle" },
    { colId: "instrumentId" },
    { colId: "faInsCode" },
    { colId: "faInsName" },
    { colId: "currentShareCount" },
    { colId: "openBuyOrder" },
    { colId: "openSellOrder" },
    { colId: "intradayBuy" },
    { colId: "intradaySell" },
    { colId: "sellableShareCount" },
    { colId: "remainAssetCount" },
    { colId: "effectiveDate" },
    { colId: "intraday-detail" },
  ],
  "user-management_logs": [
    { colId: "userId" },
    { colId: "name" },
    { colId: "typeTitle" },
    { colId: "date" },
    { colId: "clientId" },
    { colId: "succeed" },
    { colId: "ip" },
    { colId: "userAgent" },
    { colId: "browser" },
    { colId: "os" },
    { colId: "isMobile" },
    { colId: "errorMessage" },
  ],
  "user-management_roles": [
    { colId: "checkbox" },
    { colId: "id", cellRenderer: "agGroupCellRenderer" },
    { colId: "name", headerName: "نقش" },
    {
      colId: "isActive",
      cellRendererSelector: () => {
        return { component: RoleToggleButton };
      },
    },
  ],
  "user-management_roles_detail": [
    { colId: "id" },
    { colId: "serviceTitle" },
    { colId: "moduleTitle" },
    { colId: "actionTitle" },
  ],
  "user-management_users": [
    { colId: "checkbox" },
    { colId: "username", cellRenderer: "agGroupCellRenderer" },
    { colId: "phoneNumber" },
    { colId: "firstName" },
    { colId: "lastName" },
    { colId: "nationalId" },
    {
      colId: "isActive",
      cellRendererSelector: () => {
        return { component: ToggleButtonUsers };
      },
    },
    { colId: "twoFactorEnabled" },
    { colId: "lockOutEnd" },
  ],
  "user-management_users_detail": [
    { colId: "id", flex: 1 },
    { colId: "name", flex: 1 },
    {
      colId: "isActive",
      flex: 1,
      valueFormatter: (rowData: any) => {
        return rowData.data.isActive ? "فعال" : "غیر فعال";
      },
    },
  ],
};

export const generateDynamicColumnDefs = (module: ModulesType) => {
  const dynamicColumnDefs = modularColsDef[module]?.map((col: ColDefType) => {
    const { children, ...rest } = col;
    if (children) {
      return {
        ...columnModel.find((column: any) => column.colId === col.colId),
        ...rest,
        children: children.map((childCol: ColDefType) => {
          return {
            ...columnModel.find(
              (column: any) => column.colId === childCol.colId
            ),
            ...childCol,
          };
        }),
      };
    } else {
      return {
        ...columnModel.find((column: any) => column.colId === col.colId),
        ...col,
      };
    }
  });

  return dynamicColumnDefs || [];
};
