export const ModuleIdentifier = {
  DASHBOARD: "dashboard",
  USER_MANAGEMENT_users: "user-management_users",
  USER_MANAGEMENT_users_detail: "user-management_users_detail",
  USER_MANAGEMENT_roles: "user-management_roles",
  USER_MANAGEMENT_roles_detail: "user-management_roles_detail",
  USER_MANAGEMENT_logs: "user-management_logs",
  ONLINE_REGISTRATION: "online-registration",
  ONLINE_REGISTRATION_detail: "online-registration_detail",
  CUSTOMER_MANAGEMENT_customer: "customer-management_customer",
  CUSTOMER_MANAGEMENT_customer_detail: "customer-management_customer_detail",
  CUSTOMER_MANAGEMENT_private_person: "customer-management_private_person",
  CUSTOMER_MANAGEMENT_subsidiary: "customer-management_subsidiary",
  CUSTOMER_MANAGEMENT_branch: "customer-management_branch",
  CUSTOMER_MANAGEMENT_employee: "customer-management_employee",
  CUSTOMER_MANAGEMENT_businessUnit: "customer-management_businessUnit",
  CUSTOMER_MANAGEMENT_station: "customer-management_station",
  CUSTOMER_MANAGEMENT_trader: "customer-management_trader",
  CUSTOMER_MANAGEMENT_marketer: "customer-management_marketer",
  CUSTOMER_MANAGEMENT_agreement: "customer-management_agreement",
  CUSTOMER_MANAGEMENT_customerAgreement:
    "customer-management_customerAgreement",
  CUSTOMER_MANAGEMENT_contract: "customer-management_contract",
  CUSTOMER_MANAGEMENT_marketerContract: "customer-management_marketerContract",
  ONLINE_ORDERS: "online-orders",
  ONLINE_TRADES: "online-trades",
  ONLINE_TRADES_detail: "online-trades_detail",
  ONLINE_CANCEL: "online-cancel",
  ONLINE_CANCEL_detail: "online-cancel_detail",
  PORTFO_intraday: "intraday",
  PORTFO_detail: "portfo_detail",
  PORTFO_customer_portfo: "portfo-customer_portfo",
  PORTFO_asset_switch_request: "portfo-asset_switch_request",
  PORTFO_asset_switch_request_detail: "portfo-asset_switch_request_detail",
  PORTFO_customer_to_broker: "portfo-customer_to_broker",
  OMS_session: "oms-session",
  OMS_timetable: "oms-timetable",
  MARKET_RULES_MANAGEMENT: "market-rules-management",
  BOOK_BUILDING: "book-building",
  COMMISSION_MANAGEMENT_detail: "commission-management_detail",
  COMMISSION_MANAGEMENT_instrument: "commission-management_instrument",
  COMMISSION_MANAGEMENT_instrument_result:
    "commission-management_instrument_result",
  COMMISSION_MANAGEMENT_category: "commission-management_category",
  COMMISSION_MANAGEMENT_symbols: "commission-management_symbols",
  COMMISSION_MANAGEMENT_abstract_symbols:
    "commission-management_abstract_symbols",
  COMMISSION_MANAGEMENT_full_symbols: "commission-management_full_symbols",
  COMMISSION_MANAGEMENT_full_symbols_detail:
    "commission-management_full_symbols_detail",
  NETFLOW_trades_report: "netflow_trades_report",
  NETFLOW_trades_report_detail: "netflow_trades_report_detail",
  NETFLOW_rules: "netflow_rules",
  NETFLOW_rules_detail: "netflow_rules_detail",
  NETFLOW_cleared_trade: "netflow_cleared_trade",
  NETFLOW_cleared_trade_detail: "netflow_cleared_trade_detail",
  NETFLOW_clearing_Range_detail: "netflow_clearing_Range_detail",
  NETFLOW_clearing_Range: "netflow_clearing_Range",
  NETFLOW_information: "netflow_information",
  MARKETER_APP_relations: "marketer-app_relations",
  MARKETER_APP_relations_detail: "marketer-app_relations_detail",
  MARKETER_APP_relations_detail_deduction:
    "marketer-app_marketerContract_detail_deduction",
  MARKETER_APP_relations_detail_coefficient:
    "marketer-app_marketerContract_detail_coefficient",
  MARKETER_APP_recite: "marketer-app_recite",
  MARKETER_APP_subusers: "marketer-app_subusers",
  MARKETER_APP_marketerContract: "marketer-app_marketerContract",
  MARKETER_APP_marketers: "marketer-app_marketers",
  MARKETER_APP_marketerContract_detail: "marketer-app_marketerContract_detail",
  MARKETER_APP_reconcilation_detail: "marketer-app_reconcilation_detail",
  MARKETER_APP_reconcilation: "marketer-app_reconcilation",
  CSDI_PORTFO: "csdi-portfo",
  CSDI_PORTFO_asset_switch_report: "csdi-portfo_asset_switch_report",
  CSDI_PORTFO_switch_report: "csdi-portfo_switch_report",
  CSDI_PORTFO_comparison: "csdi-portfo_comparison",
  CSDI_PORTFO_freezed_asset: "csdi-portfo_freezed_asset",
} as const;
